#!/bin/bash

screen_toggle.sh -x
# trayer.sh &
/usr/bin/dropbox start &
/usr/bin/nm-applet &

[[ -e ~/wallpapers/bg.jpg ]] && feh --bg-scale ~/wallpapers/bg.jpg
[[ -e ~/wallpapers/bg.png ]] && feh --bg-scale ~/wallpapers/bg.png

#### end
