#### alacritty.max.solarized.dark.toml

general.import = ["~/.config/alacritty/alacritty.main.toml", "~/.config/alacritty/alacritty.max.toml"]

[colors.bright]
black = "0x657b83"
blue = "0x839496"
cyan = "0xd33682"
green = "0x073642"
magenta = "0xeee8d5"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x586e75"

[colors.cursor]
cursor = "0x93a1a1"
text = "0x002b36"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x93a1a1"

# [schemes.solarized_dark.bright]
# black = "0x657b83"
# blue = "0x839496"
# cyan = "0xd33682"
# green = "0x073642"
# magenta = "0xeee8d5"
# red = "0xcb4b16"
# white = "0xfdf6e3"
# yellow = "0x586e75"
# 
# [schemes.solarized_dark.cursor]
# cursor = "0x93a1a1"
# text = "0x002b36"
# 
# [schemes.solarized_dark.normal]
# black = "0x002b36"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0x6c71c4"
# red = "0xdc322f"
# white = "0x93a1a1"
# yellow = "0xb58900"
# 
# [schemes.solarized_dark.primary]
# background = "0x002b36"
# foreground = "0x93a1a1"

#### END
