#### alacritty.max.toml

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

#### END