import = ["/home/kmarzic/.config/alacritty/alacritty.main.toml", "/home/kmarzic/.config/alacritty/alacritty.scratchpad.toml"]

[colors.bright]
black = "#666666"
blue = "#0000ff"
cyan = "#00e5e5"
green = "#00d900"
magenta = "#e500e5"
red = "#e50000"
white = "#e5e5e5"
yellow = "#e5e500"

[colors.normal]
black = "#000000"
blue = "#0000b2"
cyan = "#00a6b2"
green = "#00a600"
magenta = "#b200b2"
red = "#990000"
white = "#bfbfbf"
yellow = "#999900"

[colors.primary]
background = "#000000"
foreground = "#b6b6b6"

# [schemes.ansi.bright]
# black = "#666666"
# blue = "#0000ff"
# cyan = "#00e5e5"
# green = "#00d900"
# magenta = "#e500e5"
# red = "#e50000"
# white = "#e5e5e5"
# yellow = "#e5e500"
# 
# [schemes.ansi.normal]
# black = "#000000"
# blue = "#0000b2"
# cyan = "#00a6b2"
# green = "#00a600"
# magenta = "#b200b2"
# red = "#990000"
# white = "#bfbfbf"
# yellow = "#999900"
# 
# [schemes.ansi.primary]
# background = "#000000"
# foreground = "#b6b6b6"
