#### alacritty.max.base16-atelier-savanna-light.toml

import = ["~/.config/alacritty/alacritty.main.toml", "~/.config/alacritty/alacritty.max.toml"]

[colors.bright]
black   = "0x78877d"
red     = "0xb16139"
green   = "0x489963"
yellow  = "0xa07e3b"
blue    = "0x478c90"
magenta = "0x55859b"
cyan    = "0x1c9aa0"
white   = "0x171c19"

[colors.cursor]
cursor  = "0xecf4ee"
text    = "0x526057"

[colors.normal]
black   = "0xecf4ee"
red     = "0xb16139"
green   = "0x489963"
yellow  = "0xa07e3b"
blue    = "0x478c90"
magenta = "0x55859b"
cyan    = "0x1c9aa0"
white   = "0x526057"

[colors.primary]
background = "0xecf4ee"
foreground = "0x526057"

#### END
