import = ["/home/kmarzic/.config/alacritty/alacritty.main.toml", "/home/kmarzic/.config/alacritty/alacritty.max.toml"]

[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

# [schemes.gruvbox_material_hard_dark.bright]
# black = "0x32302f"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_hard_dark.normal]
# black = "0x32302f"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_hard_dark.primary]
# background = "0x1d2021"
# foreground = "0xd4be98"
# 
# [schemes.gruvbox_material_medium_dark.bright]
# black = "0x3c3836"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_medium_dark.normal]
# black = "0x3c3836"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_medium_dark.primary]
# background = "0x282828"
# foreground = "0xd4be98"
# 
# [schemes.gruvbox_material_soft_dark.bright]
# black = "0x45403d"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_soft_dark.normal]
# black = "0x45403d"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
# 
# [schemes.gruvbox_material_soft_dark.primary]
# background = "0x32302f"
# foreground = "0xd4be98"
