#### alacritty.max.papercolor.light.toml

general.import = ["~/.config/alacritty/alacritty.main.toml", "~/.config/alacritty/alacritty.max.toml"]

[colors.bright]
black = "0x949494"
blue = "0x4271ae"
cyan = "0x3e999f"
green = "0x718c00"
magenta = "0x8959a8"
red = "0xd7005f"
white = "0x878787"
yellow = "0xd75f00"

[colors.cursor]
cursor = "0x4d4d4c"
text = "0xf3f3f3"

[colors.normal]
black = "0xededed"
blue = "0x4271ae"
cyan = "0x3e999f"
green = "0x718c00"
magenta = "0x8959a8"
red = "0xd7005f"
white = "0x4d4d4c"
yellow = "0xd75f00"

[colors.primary]
background = "0xeeeeee"
foreground = "0x4d4d4c"

# [schemes.papercolor_light_1.bright]
# black = "0x949494"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0x878787"
# yellow = "0xd75f00"
# 
# [schemes.papercolor_light_1.cursor]
# cursor = "0x4d4d4c"
# text = "0xf3f3f3"
# 
# [schemes.papercolor_light_1.normal]
# black = "0xededed"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0x4d4d4c"
# yellow = "0xd75f00"
# 
# [schemes.papercolor_light_1.primary]
# background = "0xeeeeee"
# foreground = "0x4d4d4c"
# 
# [schemes.papercolor_light_2.bright]
# black = "0xbcbcbc"
# blue = "0xd75f00"
# cyan = "0x005faf"
# green = "0xd70087"
# magenta = "0xd75f00"
# red = "0xd70000"
# white = "0x005f87"
# yellow = "0x8700af"
# 
# [schemes.papercolor_light_2.cursor]
# cursor = "0x444444"
# text = "0xeeeeee"
# 
# [schemes.papercolor_light_2.normal]
# black = "0xeeeeee"
# blue = "0x0087af"
# cyan = "0x005f87"
# green = "0x008700"
# magenta = "0x878787"
# red = "0xaf0000"
# white = "0x444444"
# yellow = "0x5f8700"
# 
# [schemes.papercolor_light_2.primary]
# background = "0xeeeeee"
# foreground = "0x444444"

#### END
